apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    name: client-pod
    component: web
spec:
  containers:
  - name: client
    image: noman2000/multi-client
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
